In [1]:
import numpy as np
from plotly.offline import plot
import plotly.graph_objs as go

In [22]:
bcg = np.loadtxt("yjj_raw_bcg.txt")
bcg = np.asarray(bcg)

In [31]:
peak_indices = np.loadtxt("peak_index.txt",dtype=np.int)
#peak_indices = np.asarray(peak_indices)

In [32]:
plot([go.Scatter(y=np.diff(peak_indices),mode="lines+markers",name="down")])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [18]:
plot([
    go.Scatter(y=bcg), 
    go.Scatter(x=peak_indices, y=bcg[peak_indices], mode="markers"),
])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [33]:
peak_intervals = np.loadtxt("peak_intervals.txt")

In [35]:
plot(go.Figure(data=[go.Scatter(y=peak_intervals,mode="lines+markers")],layout=go.Layout(yaxis=dict(range=(300, 800)))))

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [9]:
bcg.shape,peak_indices.shape

((1365838,), (2945,))

In [10]:
bcg[[1,2]]

array([-2074., -2069.])

In [74]:
bcg = np.loadtxt("bcg.txt")

In [75]:
plot([go.Scatter(y=bcg)])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [76]:
raw = np.loadtxt('raw_bcg.txt')

In [77]:
plot([go.Scatter(y=raw)])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [89]:
start = 50000
end = start + 300000
plot([go.Scatter(y=raw[start:end], name="raw"), 
      go.Scatter(y=bcg[start:end], name="bcg"), 
      go.Scatter(y=np.asarray(bcg_py[start:end]),name="bcg_py")])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [80]:
from scipy.signal import lfilter

In [81]:
b = np.loadtxt("../data/bandpass_b_500.csv", delimiter=',')
a = np.loadtxt("../data/bandpass_a_500.csv", delimiter=',')

In [82]:
from scipy.signal import lfilter

In [83]:
bcg_py = lfilter(b, a, raw)

In [19]:
plot([go.Scatter(y=bcg_py)])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [25]:
b

array([ 0.00277947,  0.        , -0.00833841,  0.        ,  0.00833841,
        0.        , -0.00277947])

In [21]:
a

array([  1.        ,  -5.37926038,  12.0782021 , -14.49605185,
         9.81178146,  -3.55191271,   0.53724138])

In [62]:
bcg_py[:100]

array([   -5.81187287,   -37.06711194,  -117.55902851,  -257.30479954,
        -450.30773473,  -681.43735713,  -931.78707946, -1182.55958041,
       -1417.51888129, -1624.33124205, -1795.07092497, -1925.99388348,
       -2016.88749835, -2070.3416708 , -2090.95923509, -2084.53042353,
       -2057.37257165, -2015.82791883, -1965.78946322, -1912.34532892,
       -1859.59118702, -1810.48042736, -1766.7741957 , -1729.20720143,
       -1697.71271   , -1671.61789294, -1649.9281212 , -1631.61751747,
       -1615.75140228, -1601.54174791, -1588.38928745, -1575.79732992,
       -1563.2704039 , -1550.34074405, -1536.5731978 , -1521.55443624,
       -1505.0721086 , -1487.25614055, -1468.45030485, -1449.08167175,
       -1429.62778508, -1410.49492269, -1391.8804117 , -1373.78869629,
       -1356.09345992, -1338.57477144, -1321.04569059, -1303.47862751,
       -1285.97467547, -1268.70524857, -1251.89501953, -1235.711298  ,
       -1220.149881  , -1205.06343718, -1190.21323486, -1175.298089  ,
      

In [63]:
bcg[:100]

array([   -5.81187,   -37.0671 ,  -117.559  ,  -257.305  ,  -450.308  ,
        -681.437  ,  -931.787  , -1182.56   , -1417.52   , -1624.33   ,
       -1795.07   , -1925.99   , -2016.89   , -2070.34   , -2090.96   ,
       -2084.52   , -2057.36   , -2015.81   , -1965.76   , -1912.3    ,
       -1859.53   , -1810.39   , -1766.65   , -1729.04   , -1697.49   ,
       -1671.32   , -1649.55   , -1631.14   , -1615.16   , -1600.81   ,
       -1587.5    , -1574.72   , -1561.99   , -1548.83   , -1534.81   ,
       -1519.51   , -1502.71   , -1484.55   , -1465.37   , -1445.6    ,
       -1425.71   , -1406.11   , -1386.99   , -1368.36   , -1350.09   ,
       -1331.95   , -1313.77   , -1295.52   , -1277.28   , -1259.24   ,
       -1241.62   , -1224.58   , -1208.13   , -1192.1    , -1176.27   ,
       -1160.32   , -1144.02   , -1127.28   , -1110.17   , -1092.86   ,
       -1075.6    , -1058.62   , -1041.97   , -1025.56   , -1009.24   ,
        -992.751  ,  -975.892  ,  -958.625  ,  -941.062  ,  -923

In [78]:
start = 0
end = start + 100000
plot([go.Scatter(y=bcg_py[start:end], mode="lines",name="py"), go.Scatter(y=bcg[start:end],mode="lines",name="cpp"),
     go.Scatter(y=np.asarray(raw[start:end])+2000)])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [34]:
len(b)

7

In [59]:
bcg[3]

-257.305

In [61]:
bcg_py[0]

-5.81187287036003

# debug findpeaks offline

In [90]:
signal = np.loadtxt("debug.signal")

In [93]:
plot([go.Scatter(y=signal, mode="lines+markers"),
     go.Scatter(y=np.diff(signal))])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

# debug AutoPeaksMaster

In [94]:
peak_indices = np.loadtxt("heart.txt")

In [95]:
raw = np.loadtxt('raw_bcg.txt')

In [96]:
intervals = 
plot([go.Scatter(y=np.diff(peak_indices), mode="lines+markers")])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [97]:
intervals = np.loadtxt("intervals.txt")

In [99]:
plot([go.Scatter(y=intervals, mode="lines+markers")])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [104]:
from bcg import load_bcg

In [105]:
yjj = load_bcg("yjj.txt", filter=False, notch=False, resp=False, offset=9558-396)

In [107]:
plot([go.Scatter(y=yjj)])

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [108]:
np.savetxt("yjj_raw_bcg.txt", yjj, delimiter='\n')

In [29]:
yjj_intervals = np.loadtxt("yjj_intervals.txt")

In [30]:
plot(go.Figure(data=[go.Scatter(y=yjj_intervals, mode="lines+markers")], 
     layout=go.Layout(yaxis=dict(range=(300,800)))))

'file:///home/guo/Github/BCGHeart/embedding/test/temp-plot.html'

In [125]:
len(yjj_intervals)

3198